# Generated by Django 5.1.3 on 2024-12-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_latitude_customer_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='location_updates_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
