# Generated by Django 5.1.3 on 2024-12-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_location_updates_count_customer_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ที่อยู่'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location_updates_count',
            field=models.PositiveIntegerField(default=0, verbose_name='จำนวนครั้งที่อัพเดทที่อยู่'),
        ),
    ]
