# Generated by Django 5.1.3 on 2024-12-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='project_category',
            field=models.CharField(choices=[('SMALL', 'บ้านหลังเล็ก'), ('LARGE', 'บ้านหลังใหญ่')], default='OTHER', max_length=10, verbose_name='ขนาดบ้าน'),
        ),
        migrations.AddField(
            model_name='customer',
            name='project_type',
            field=models.CharField(choices=[('MANTANA', 'มัณฑนา'), ('PRUKLADA', 'พฤกษ์ลดา'), ('INIZIO', 'INIZIO'), ('VILLAGGIO', 'Villaggio'), ('SIVALI', 'สีวลี'), ('CHAIYAPRUEK', 'ชัยพฤกษ์'), ('VIVE', 'VIVE'), ('NANTAWAN', 'นันทวัน'), ('LADAWAN', 'ลดาวัลย์'), ('OTHER', 'อื่นๆ')], default='OTHER', max_length=20, verbose_name='ประเภทโครงการ'),
        ),
    ]
