# Generated by Django 5.1.3 on 2024-12-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customer_project_category_customer_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันหมดประกัน'),
        ),
        migrations.AddField(
            model_name='customer',
            name='warranty_status',
            field=models.CharField(choices=[('ACTIVE', 'อยู่ในประกัน'), ('EXPIRED', 'หมดประกัน'), ('NONE', 'ไม่มีประกัน')], default='NONE', max_length=10, verbose_name='สถานะประกัน'),
        ),
    ]
