# Generated by Django 5.1.3 on 2024-11-26 04:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=50, unique=True, verbose_name='เลขที่งาน')),
                ('project_code', models.CharField(max_length=50, verbose_name='รหัสโครงการ')),
                ('plot_number', models.CharField(max_length=50, verbose_name='เลขที่แปลง')),
                ('reported_issue', models.TextField(verbose_name='ปัญหาที่แจ้ง')),
                ('appointment_date', models.DateField(verbose_name='วันที่นัดหมาย')),
                ('appointment_time', models.TimeField(verbose_name='เวลานัดหมาย')),
                ('completion_status', models.CharField(choices=[('completed', 'เสร็จสมบูรณ์'), ('partial', 'เสร็จบางส่วน'), ('pending_parts', 'รออะไหล่'), ('cancelled', 'ยกเลิก')], max_length=50, verbose_name='สถานะการดำเนินการ')),
                ('faulty_equipment', models.TextField(blank=True, verbose_name='อุปกรณ์ที่เสีย')),
                ('cause', models.TextField(blank=True, verbose_name='สาเหตุ')),
                ('solution', models.TextField(blank=True, verbose_name='การแก้ไข')),
                ('service_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ค่าบริการ')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่บันทึก')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุด')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='accounts.customer')),
            ],
            options={
                'verbose_name': 'บันทึกการซ่อม',
                'verbose_name_plural': 'บันทึกการซ่อม',
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('repair', 'ซ่อมแซม'), ('install', 'ติดตั้ง'), ('inspect', 'ตรวจสอบ')], max_length=20)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(verbose_name='รายละเอียดปัญหา')),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('assigned', 'มอบหมายงานแล้ว'), ('in_progress', 'กำลังดำเนินการ'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='accounts.customer')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'การแจ้งซ่อม',
                'verbose_name_plural': 'การแจ้งซ่อม',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_proposals', to='service.servicerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_images/%Y/%m/', verbose_name='รูปภาพ')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='คำอธิบายรูปภาพ')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='service.servicerequest', verbose_name='การแจ้งซ่อม')),
            ],
            options={
                'verbose_name': 'รูปภาพการซ่อม',
                'verbose_name_plural': 'รูปภาพการซ่อม',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianJobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('assigned', 'มอบหมายงานแล้ว'), ('in_progress', 'กำลังดำเนินการ'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก')], max_length=20, verbose_name='สถานะ')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาอัพเดท')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='service.servicerequest')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'สถานะงานช่าง',
                'verbose_name_plural': 'สถานะงานช่าง',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_proposals', to='service.servicerequest')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ประมาณการค่าใช้จ่าย')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('response_date', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ตอบกลับ')),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_response', to='service.servicerequest')),
            ],
            options={
                'verbose_name': 'การตอบกลับของช่าง',
                'verbose_name_plural': 'การตอบกลับของช่าง',
                'ordering': ['-response_date'],
            },
        ),
    ]
