# Generated by Django 5.1.3 on 2024-11-26 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(upload_to='service_images/'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='service_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicerequest'),
        ),
    ]
