# Generated by Django 5.1.3 on 2024-11-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_serviceimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
