# Generated by Django 5.1.3 on 2024-11-27 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_servicerequest_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='service_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_images', to='service.servicerequest'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(choices=[('repair', 'แจ้งซ่อม'), ('install', 'ซื้ออุปกรณ์'), ('all_in', 'ต้องการแจ้งซ่อมและซื้ออุปกรณ์')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ'), ('assigned', 'มอบหมายงานแล้ว'), ('accepted', 'รับงาน'), ('traveling', 'กำลังเดินทาง'), ('arrived', 'ถึงจุดหมาย'), ('fixing', 'กำลังแก้ไข'), ('completed_cash', 'เสร็จสิ้น - เก็บเงินหน้างาน'), ('completed_call', 'เสร็จสิ้น - โทรเก็บเงิน'), ('cancelled', 'ยกเลิก'), ('rescheduled', 'เลื่อนนัด')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='technicianjobstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ'), ('assigned', 'มอบหมายงานแล้ว'), ('accepted', 'รับงาน'), ('traveling', 'กำลังเดินทาง'), ('arrived', 'ถึงจุดหมาย'), ('fixing', 'กำลังแก้ไข'), ('completed_cash', 'เสร็จสิ้น - เก็บเงินหน้างาน'), ('completed_call', 'เสร็จสิ้น - โทรเก็บเงิน'), ('cancelled', 'ยกเลิก'), ('rescheduled', 'เลื่อนนัด')], max_length=20, verbose_name='สถานะ'),
        ),
    ]
