# Generated by Django 5.1.3 on 2024-11-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_serviceimage_service_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='ยืนยันโดยฝ่ายบริการ'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ'), ('confirmed', 'ยืนยันการแจ้งซ่อม'), ('assigned', 'มอบหมายงานแล้ว'), ('accepted', 'รับงาน'), ('traveling', 'กำลังเดินทาง'), ('arrived', 'ถึงจุดหมาย'), ('fixing', 'กำลังแก้ไข'), ('completed_cash', 'เสร็จสิ้น - เก็บเงินหน้างาน'), ('completed_call', 'เสร็จสิ้น - โทรเก็บเงิน'), ('cancelled', 'ยกเลิก'), ('rescheduled', 'เลื่อนนัด')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='technicianjobstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ'), ('confirmed', 'ยืนยันการแจ้งซ่อม'), ('assigned', 'มอบหมายงานแล้ว'), ('accepted', 'รับงาน'), ('traveling', 'กำลังเดินทาง'), ('arrived', 'ถึงจุดหมาย'), ('fixing', 'กำลังแก้ไข'), ('completed_cash', 'เสร็จสิ้น - เก็บเงินหน้างาน'), ('completed_call', 'เสร็จสิ้น - โทรเก็บเงิน'), ('cancelled', 'ยกเลิก'), ('rescheduled', 'เลื่อนนัด')], max_length=20, verbose_name='สถานะ'),
        ),
    ]
