# Generated by Django 5.1.3 on 2024-12-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianjobstatus',
            name='status',
            field=models.CharField(choices=[('accepted', 'รับงาน'), ('cancelled', 'ยกเลิก'), ('rescheduled', 'เลื่อนนัด')], max_length=20, verbose_name='สถานะ'),
        ),
    ]
