# Generated by Django 5.1.3 on 2024-12-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_servicerequest_warranty_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='warranty_status',
            field=models.CharField(blank=True, choices=[('อยู่ในประกัน', 'อยู่ในประกัน'), ('อยู่ในประกัน', 'ไม่อยู่ในประกัน')], max_length=20, null=True),
        ),
    ]
