# Generated by Django 5.1.3 on 2024-12-06 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_delete_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serviceimage',
            unique_together={('service_request', 'image')},
        ),
    ]
