# Generated by Django 5.1.3 on 2024-12-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_alter_serviceimage_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending_advice', 'รอคำแนะนำจากช่าง'), ('advice_given', 'ได้รับคำแนะนำแล้ว'), ('pending', 'รอดำเนินการ'), ('confirmed', 'ยืนยันการแจ้งซ่อม'), ('assigned', 'มอบหมายงานแล้ว'), ('accepted', 'รับงาน'), ('traveling', 'กำลังเดินทาง'), ('arrived', 'ถึงจุดหมาย'), ('fixing', 'กำลังแก้ไข'), ('completed_cash', 'เสร็จสิ้น - เก็บเงินหน้างาน'), ('completed_call', 'เสร็จสิ้น - โทรเก็บเงิน'), ('cancelled', 'ยกเลิก'), ('rescheduled', 'เลื่อนนัด')], default='pending', max_length=20),
        ),
    ]
