# Generated by Django 5.1.3 on 2024-12-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='customer_confirmed',
            field=models.BooleanField(default=False, verbose_name='ลูกค้ายืนยันการดำเนินการ'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ประมาณการค่าใช้จ่าย'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='need_advice',
            field=models.BooleanField(default=False, help_text='เลือกตัวเลือกนี้หากต้องการให้ช่างแนะนำก่อนดำเนินการ', verbose_name='ต้องการคำแนะนำจากช่าง'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='technician_advice',
            field=models.TextField(blank=True, null=True, verbose_name='คำแนะนำจากช่าง'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ'), ('confirmed', 'ยืนยันการแจ้งซ่อม'), ('assigned', 'มอบหมายงานแล้ว'), ('accepted', 'รับงาน'), ('traveling', 'กำลังเดินทาง'), ('arrived', 'ถึงจุดหมาย'), ('fixing', 'กำลังแก้ไข'), ('completed_cash', 'เสร็จสิ้น - เก็บเงินหน้างาน'), ('completed_call', 'เสร็จสิ้น - โทรเก็บเงิน'), ('cancelled', 'ยกเลิก'), ('rescheduled', 'เลื่อนนัด')], default='pending', max_length=20),
        ),
    ]
