# Generated by Django 5.1.3 on 2024-12-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_alter_technicianresponse_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianresponse',
            name='response_text',
        ),
        migrations.AddField(
            model_name='technicianresponse',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='รายละเอียดการตอบกลับ'),
        ),
        migrations.AddField(
            model_name='technicianresponse',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ประมาณการค่าใช้จ่าย'),
        ),
        migrations.AddField(
            model_name='technicianresponse',
            name='service_type',
            field=models.CharField(blank=True, choices=[('normal', 'ระบบไฟปกติ'), ('full_checkup', 'ระบบ Full Check Up'), ('air_flow', 'ระบบ Air flow/Air Plus'), ('checkup_air_plus', 'ระบบ Check up Program Air plus')], max_length=50, null=True, verbose_name='ประเภทการซ่อม'),
        ),
    ]
