# Generated by Django 5.1.3 on 2024-12-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_alter_technicianjobstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่สิ้นสุดประกัน'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='warranty_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่เริ่มประกัน'),
        ),
    ]
