# Generated by Django 5.1.3 on 2024-12-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_servicerequest_warranty_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ'), ('assigned', 'มอบหมายงานแล้ว'), ('pending_advice', 'รอคำแนะนำจากช่าง'), ('advice_given', 'ให้คำแนะนำแล้ว'), ('accepted', 'รับงาน'), ('traveling', 'กำลังเดินทาง'), ('arrived', 'ถึงจุดหมาย'), ('fixing', 'กำลังแก้ไข'), ('completed_cash', 'เสร็จสิ้น - เก็บเงินหน้างาน'), ('completed_call', 'เสร็จสิ้น - โทรเก็บเงิน'), ('cancelled', 'ยกเลิก'), ('rescheduled', 'เลื่อนนัด')], default='pending', max_length=20),
        ),
    ]
