# Generated by Django 5.1.3 on 2024-12-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='warranty_status',
            field=models.CharField(choices=[('in_warranty', 'อยู่ในประกัน'), ('out_of_warranty', 'ไม่อยู่ในประกัน'), ('pending_warranty', 'รอการตัดสินใจ')], default='pending_warranty', max_length=20, verbose_name='สถานะประกัน'),
        ),
    ]
