# Generated by Django 5.1.3 on 2024-12-23 07:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_alter_servicerequest_warranty_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerecord',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'บันทึกการบริการ', 'verbose_name_plural': 'บันทึกการบริการ'},
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='cause',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='faulty_equipment',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='record_date',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='reported_issue',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='service_cost',
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='additional_notes',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุเพิ่มเติม'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='จำนวนเงิน'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='bill_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เลขที่บิล'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='cause_found',
            field=models.TextField(blank=True, null=True, verbose_name='สาเหตุที่ตรวจพบ'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='เบอร์ติดต่อลูกค้า'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='วันที่'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='อาการที่รับแจ้ง'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='equipment_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='สถานะวัสดุ/อุปกรณ์'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='house_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='บ้านเลขที่'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='house_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='แบบบ้าน'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='month',
            field=models.IntegerField(blank=True, null=True, verbose_name='เดือน'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='project_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อโครงการ'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='sequence',
            field=models.IntegerField(blank=True, null=True, verbose_name='ลำดับ'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='service_images',
            field=models.TextField(blank=True, null=True, verbose_name='ลิงก์รูปภาพ'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ'), ('in_progress', 'กำลังดำเนินการ'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='technician_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อเจ้าหน้าที่'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='technician_names',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ชื่อช่างผู้ดำเนินการ'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='technician_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='เบอร์ติดต่อเจ้าหน้าที่'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='เวลา'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='transfer_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่โอน'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='warranty_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่หมดประกัน'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='ปี พ.ศ.'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='appointment_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันนัด'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='appointment_time',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='เวลานัด'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='completion_status',
            field=models.BooleanField(default=False, verbose_name='สถานะจบงาน'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='job_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='เลขงาน'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='plot_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เลขที่แปลง'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='project_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='รหัสโครงการ'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='solution',
            field=models.TextField(blank=True, null=True, verbose_name='การแก้ไข'),
        ),
    ]
