# Generated by Django 5.1.3 on 2024-12-24 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0028_alter_servicerequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='cost_note',
            field=models.TextField(blank=True, verbose_name='หมายเหตุค่าใช้จ่าย'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='cost_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่กำหนดค่าใช้จ่าย'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='cost_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_updates', to=settings.AUTH_USER_MODEL, verbose_name='ผู้กำหนดค่าใช้จ่าย'),
        ),
    ]
