# Generated by Django 5.1.3 on 2025-01-02 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customer_warranty_expiry_date_and_more'),
        ('service', '0030_servicerequest_ac_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='additional_notes',
            field=models.TextField(blank=True, default='', null=True, verbose_name='หมายเหตุเพิ่มเติม'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='จำนวนเงิน'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True, verbose_name='เวลานัด'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='bill_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='เลขที่บิล'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='cause_found',
            field=models.TextField(blank=True, default='', null=True, verbose_name='สาเหตุที่ตรวจพบ'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='completion_status',
            field=models.BooleanField(default=False, null=True, verbose_name='สถานะจบงาน'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='ลูกค้า'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='date',
            field=models.DateField(null=True, verbose_name='วันที่'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='อาการที่แจ้ง'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='equipment_status',
            field=models.TextField(blank=True, default='', null=True, verbose_name='วัสดุ/อุปกรณ์ที่ผิดปกติ'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='house_number',
            field=models.CharField(max_length=50, null=True, verbose_name='บ้านเลขที่'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='house_type',
            field=models.CharField(max_length=50, null=True, verbose_name='แบบบ้าน'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='job_number',
            field=models.CharField(max_length=50, null=True, verbose_name='เลขงาน'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='notes',
            field=models.TextField(blank=True, default='', null=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='plot_number',
            field=models.CharField(max_length=50, null=True, verbose_name='แปลง'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='project_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสโครงการ'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='project_name',
            field=models.CharField(max_length=100, null=True, verbose_name='โครงการ'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='sequence',
            field=models.IntegerField(null=True, verbose_name='ลำดับ'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='service_images',
            field=models.TextField(blank=True, default='', null=True, verbose_name='ลิงก์รูปภาพ'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='solution',
            field=models.TextField(blank=True, default='', null=True, verbose_name='การแก้ไข'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='status',
            field=models.CharField(max_length=50, null=True, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='technician_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อช่าง'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='technician_names',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='รายชื่อช่าง'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='technician_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์ติดต่อช่าง'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='เวลา'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='year',
            field=models.CharField(max_length=4, null=True, verbose_name='ปี พ.ศ.'),
        ),
    ]
