# Generated by Django 5.1.3 on 2025-01-06 01:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0031_remove_servicerecord_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='time_created',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='เวลาสร้าง'),
            preserve_default=False,
        ),
    ]
