# Generated by Django 5.1.3 on 2025-01-06 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0032_servicerequest_time_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='time_created',
        ),
    ]
