# Generated by Django 5.1.3 on 2025-01-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0033_remove_servicerequest_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ'), ('assigned', 'มอบหมายงานแล้ว'), ('pending_advice', 'รอคำปรึกษาจากช่าง'), ('advice_given', 'ให้คำปรึกษาแล้ว'), ('confirmed', 'ยืนยันการแจ้งซ่อม'), ('accepted', 'รับงาน'), ('traveling', 'กำลังเดินทาง'), ('arrived', 'ถึงจุดหมาย'), ('fixing', 'กำลังแก้ไข'), ('completed_cash', 'เสร็จสิ้น - เก็บเงินหน้างาน'), ('completed_call', 'เสร็จสิ้น - โทรเก็บเงิน'), ('cancelled', 'ยกเลิก'), ('rescheduled', 'เลื่อนนัด')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='technicianjobstatus',
            name='status',
            field=models.CharField(choices=[('confirmed', 'ยืนยันการแจ้งซ่อม'), ('accepted', 'รับงาน'), ('traveling', 'กำลังเดินทาง'), ('arrived', 'ถึงจุดหมาย'), ('fixing', 'กำลังแก้ไข'), ('completed_cash', 'เสร็จสิ้น - เก็บเงินหน้างาน'), ('completed_call', 'เสร็จสิ้น - โทรเก็บเงิน'), ('cancelled', 'ยกเลิก'), ('rescheduled', 'เลื่อนนัด')], max_length=20, verbose_name='สถานะ'),
        ),
    ]
